---
  - name: "Prepare web server"
    hosts: awx-client.localdomain
    remote_user: jdoe
    become: true

    tasks:
      - name: "Install nginx"
        yum:
          name: nginx
          state: latest