---
  - name: "Prepare web server"
    hosts: awx-client.localdomain
    remote_user: jdoe
    become: true

    vars:
      # Used for Nginx configuration
      src_config_folder: ../default-configs
      dst_config_folder: /etc/nginx

      # For both configuration and site templates
      src_template_folder: ../templates

      # Used for site configuration
      dst_template_config_folder: /etc/nginx/conf.d

      # Used for html, php etc.
      dst_template_site_folder: /usr/share/nginx/html

    tasks:
      - name: "Install nginx"
        yum:
          name: nginx
          state: latest

      - name: "Start nginx"
        service:
          name: nginx
          state: started

      - name: "Copy default Nginx configuration"
        copy:
          src: "{{ src_config_folder }}/nginx.conf"
          dest: "{{ dst_config_folder }}"
        notify:
          - Restart Nginx

      - name: "Generate Nginx site configuration"
        template:
          src: "{{ src_template_folder }}/default.conf.j2"
          dest: "{{ dst_template_config_folder }}/default.conf"
        notify:
          - Restart Nginx

      - name: "Generate html files"
        template:
          src: "{{ src_template_folder }}/sample-page.j2"
          dest: "{{ dst_template_site_folder }}/sample-page.html"
        notify:
          - Restart Nginx

    handlers:
      - name: "Restart Nginx"
        service:
          name: nginx
          state: restarted
