---
  - name: "Prepare web server"
    hosts: awx-client.localdomain
    remote_user: jdoe
    become: true

    vars:
      source_folder: ./templates
      dest_folder: /usr/share/nginx/html

    tasks:
      - name: "Install nginx"
        yum:
          name: nginx
          state: latest

      - name: "Start nginx"
        service:
          name: nginx
          state: started

      - name: "Copy site contents"
        copy:
          src: "{{ source_folder }}"
          dest: "{{ dest_folder }}"
        notify:
          - Restart Nginx

    handlers:
      - name: "Restart Nginx"
        service:
          name: nginx
          state: restarted